# Generated by Django 5.1.3 on 2024-11-15 18:41

import django.db.models.deletion
import djangoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[djangoapp.models.validate_price_positive])),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROCESS', 'In Process'), ('SENT', 'Sent'), ('COMPLETED', 'Completed')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.customer')),
                ('products', models.ManyToManyField(to='djangoapp.product')),
            ],
        ),
    ]
