# Generated by Django 5.1.3 on 2024-11-15 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('address', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.CharField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.customer')),
                ('products', models.ManyToManyField(to='djangoapp.product')),
            ],
        ),
    ]
