name: Software engineering lab 9

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:         
  docs:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set up environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
          
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          
      - name: Generate API documentation
        run: |
          source venv/bin/activate
          python djangoproject/manage.py generateschema > docs.json
          
      - name: Check file status
        run: |
          git status
          git diff docs.json
          
      - name: Check for changes
        id: changes-check
        continue-on-error: true
        run: |
          git diff docs.json
          git add docs.json
          git diff docs.json
          git diff --cached docs.json || echo "Changes detected."
          echo "Checked for changes."
      
      - name: Stop if no changes to commit
        if: ${{ steps.changes-check.outcome != 'success' }}
        run: echo "No changes detected. Skipping commit and push."
        
      - name: Proceed if changes to commit
        if: ${{ steps.changes-check.outcome == 'success' }} 
        run: echo "Changes detected. Proceeding to commit and push."
        
      - name: Commit and push documentation
        if: ${{ steps.changes-check.outcome == 'success' }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "Updated documentation"
          git push origin main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      

          